package com.chy.dao;

import com.chy.bean.fill_gps_rucheng;
import com.chy.bean.fill_gps_ruchengExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface fill_gps_ruchengMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fill_gps_rucheng04_01
     *
     * @mbg.generated Fri May 31 09:40:50 CST 2019
     */
    long countByExample(fill_gps_ruchengExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fill_gps_rucheng04_01
     *
     * @mbg.generated Fri May 31 09:40:50 CST 2019
     */
    int deleteByExample(fill_gps_ruchengExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fill_gps_rucheng04_01
     *
     * @mbg.generated Fri May 31 09:40:50 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fill_gps_rucheng04_01
     *
     * @mbg.generated Fri May 31 09:40:50 CST 2019
     */
    int insert(fill_gps_rucheng record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fill_gps_rucheng04_01
     *
     * @mbg.generated Fri May 31 09:40:50 CST 2019
     */
    int insertSelective(fill_gps_rucheng record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fill_gps_rucheng04_01
     *
     * @mbg.generated Fri May 31 09:40:50 CST 2019
     */
    List<fill_gps_rucheng> selectByExample(fill_gps_ruchengExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fill_gps_rucheng04_01
     *
     * @mbg.generated Fri May 31 09:40:50 CST 2019
     */
    fill_gps_rucheng selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fill_gps_rucheng04_01
     *
     * @mbg.generated Fri May 31 09:40:50 CST 2019
     */
    int updateByExampleSelective(@Param("record") fill_gps_rucheng record, @Param("example") fill_gps_ruchengExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fill_gps_rucheng04_01
     *
     * @mbg.generated Fri May 31 09:40:50 CST 2019
     */
    int updateByExample(@Param("record") fill_gps_rucheng record, @Param("example") fill_gps_ruchengExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fill_gps_rucheng04_01
     *
     * @mbg.generated Fri May 31 09:40:50 CST 2019
     */
    int updateByPrimaryKeySelective(fill_gps_rucheng record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fill_gps_rucheng04_01
     *
     * @mbg.generated Fri May 31 09:40:50 CST 2019
     */
    int updateByPrimaryKey(fill_gps_rucheng record);



    List<fill_gps_rucheng>  selectplateNum(@Param("table") String table);

    List<fill_gps_rucheng>  selectlongandlati(@Param("table") String table,@Param("platenum")String platenum);


}