package com.chy.bean;

import java.util.Date;

public class fill_gps_rucheng {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fill_gps_rucheng04_01.id
     *
     * @mbg.generated Fri May 31 09:40:50 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fill_gps_rucheng04_01.selfNum
     *
     * @mbg.generated Fri May 31 09:40:50 CST 2019
     */
    private String selfnum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fill_gps_rucheng04_01.plateNum
     *
     * @mbg.generated Fri May 31 09:40:50 CST 2019
     */
    private String platenum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fill_gps_rucheng04_01.terminal
     *
     * @mbg.generated Fri May 31 09:40:50 CST 2019
     */
    private String terminal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fill_gps_rucheng04_01.latitude
     *
     * @mbg.generated Fri May 31 09:40:50 CST 2019
     */
    private Double latitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fill_gps_rucheng04_01.longitude
     *
     * @mbg.generated Fri May 31 09:40:50 CST 2019
     */
    private Double longitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fill_gps_rucheng04_01.speed
     *
     * @mbg.generated Fri May 31 09:40:50 CST 2019
     */
    private String speed;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fill_gps_rucheng04_01.direction
     *
     * @mbg.generated Fri May 31 09:40:50 CST 2019
     */
    private String direction;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fill_gps_rucheng04_01.altitude
     *
     * @mbg.generated Fri May 31 09:40:50 CST 2019
     */
    private String altitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fill_gps_rucheng04_01.routeName
     *
     * @mbg.generated Fri May 31 09:40:50 CST 2019
     */
    private String routename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fill_gps_rucheng04_01.createTime
     *
     * @mbg.generated Fri May 31 09:40:50 CST 2019
     */
    private Date createtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fill_gps_rucheng04_01.id
     *
     * @return the value of fill_gps_rucheng04_01.id
     *
     * @mbg.generated Fri May 31 09:40:50 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fill_gps_rucheng04_01.id
     *
     * @param id the value for fill_gps_rucheng04_01.id
     *
     * @mbg.generated Fri May 31 09:40:50 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fill_gps_rucheng04_01.selfNum
     *
     * @return the value of fill_gps_rucheng04_01.selfNum
     *
     * @mbg.generated Fri May 31 09:40:50 CST 2019
     */
    public String getSelfnum() {
        return selfnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fill_gps_rucheng04_01.selfNum
     *
     * @param selfnum the value for fill_gps_rucheng04_01.selfNum
     *
     * @mbg.generated Fri May 31 09:40:50 CST 2019
     */
    public void setSelfnum(String selfnum) {
        this.selfnum = selfnum == null ? null : selfnum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fill_gps_rucheng04_01.plateNum
     *
     * @return the value of fill_gps_rucheng04_01.plateNum
     *
     * @mbg.generated Fri May 31 09:40:50 CST 2019
     */
    public String getPlatenum() {
        return platenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fill_gps_rucheng04_01.plateNum
     *
     * @param platenum the value for fill_gps_rucheng04_01.plateNum
     *
     * @mbg.generated Fri May 31 09:40:50 CST 2019
     */
    public void setPlatenum(String platenum) {
        this.platenum = platenum == null ? null : platenum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fill_gps_rucheng04_01.terminal
     *
     * @return the value of fill_gps_rucheng04_01.terminal
     *
     * @mbg.generated Fri May 31 09:40:50 CST 2019
     */
    public String getTerminal() {
        return terminal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fill_gps_rucheng04_01.terminal
     *
     * @param terminal the value for fill_gps_rucheng04_01.terminal
     *
     * @mbg.generated Fri May 31 09:40:50 CST 2019
     */
    public void setTerminal(String terminal) {
        this.terminal = terminal == null ? null : terminal.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fill_gps_rucheng04_01.latitude
     *
     * @return the value of fill_gps_rucheng04_01.latitude
     *
     * @mbg.generated Fri May 31 09:40:50 CST 2019
     */
    public Double getLatitude() {
        return latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fill_gps_rucheng04_01.latitude
     *
     * @param latitude the value for fill_gps_rucheng04_01.latitude
     *
     * @mbg.generated Fri May 31 09:40:50 CST 2019
     */
    public void setLatitude(Double latitude) {
        this.latitude = latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fill_gps_rucheng04_01.longitude
     *
     * @return the value of fill_gps_rucheng04_01.longitude
     *
     * @mbg.generated Fri May 31 09:40:50 CST 2019
     */
    public Double getLongitude() {
        return longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fill_gps_rucheng04_01.longitude
     *
     * @param longitude the value for fill_gps_rucheng04_01.longitude
     *
     * @mbg.generated Fri May 31 09:40:50 CST 2019
     */
    public void setLongitude(Double longitude) {
        this.longitude = longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fill_gps_rucheng04_01.speed
     *
     * @return the value of fill_gps_rucheng04_01.speed
     *
     * @mbg.generated Fri May 31 09:40:50 CST 2019
     */
    public String getSpeed() {
        return speed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fill_gps_rucheng04_01.speed
     *
     * @param speed the value for fill_gps_rucheng04_01.speed
     *
     * @mbg.generated Fri May 31 09:40:50 CST 2019
     */
    public void setSpeed(String speed) {
        this.speed = speed == null ? null : speed.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fill_gps_rucheng04_01.direction
     *
     * @return the value of fill_gps_rucheng04_01.direction
     *
     * @mbg.generated Fri May 31 09:40:50 CST 2019
     */
    public String getDirection() {
        return direction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fill_gps_rucheng04_01.direction
     *
     * @param direction the value for fill_gps_rucheng04_01.direction
     *
     * @mbg.generated Fri May 31 09:40:50 CST 2019
     */
    public void setDirection(String direction) {
        this.direction = direction == null ? null : direction.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fill_gps_rucheng04_01.altitude
     *
     * @return the value of fill_gps_rucheng04_01.altitude
     *
     * @mbg.generated Fri May 31 09:40:50 CST 2019
     */
    public String getAltitude() {
        return altitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fill_gps_rucheng04_01.altitude
     *
     * @param altitude the value for fill_gps_rucheng04_01.altitude
     *
     * @mbg.generated Fri May 31 09:40:50 CST 2019
     */
    public void setAltitude(String altitude) {
        this.altitude = altitude == null ? null : altitude.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fill_gps_rucheng04_01.routeName
     *
     * @return the value of fill_gps_rucheng04_01.routeName
     *
     * @mbg.generated Fri May 31 09:40:50 CST 2019
     */
    public String getRoutename() {
        return routename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fill_gps_rucheng04_01.routeName
     *
     * @param routename the value for fill_gps_rucheng04_01.routeName
     *
     * @mbg.generated Fri May 31 09:40:50 CST 2019
     */
    public void setRoutename(String routename) {
        this.routename = routename == null ? null : routename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fill_gps_rucheng04_01.createTime
     *
     * @return the value of fill_gps_rucheng04_01.createTime
     *
     * @mbg.generated Fri May 31 09:40:50 CST 2019
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fill_gps_rucheng04_01.createTime
     *
     * @param createtime the value for fill_gps_rucheng04_01.createTime
     *
     * @mbg.generated Fri May 31 09:40:50 CST 2019
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }
}